# Generated by Django 5.1.4 on 2025-01-18 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Anime Tag',
                'verbose_name_plural': 'Anime Tags',
                'ordering': ['tag_name'],
                'unique_together': {('tag_name',)},
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='anime_images')),
                ('year', models.PositiveSmallIntegerField()),
                ('age_rating', models.PositiveSmallIntegerField()),
                ('season', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime_tags', models.ManyToManyField(related_name='anime_tags', to='anime_app.animetags')),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animes',
                'ordering': ['name'],
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('url_video', models.URLField()),
                ('studio', models.CharField(blank=True, max_length=255, null=True)),
                ('quality', models.CharField(choices=[('240', '240'), ('360', '360'), ('480', '480'), ('720', '720'), ('1080', '1080')], default='240', max_length=100)),
                ('part', models.IntegerField()),
                ('anime_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='anime_app.anime')),
            ],
            options={
                'verbose_name': 'anime',
                'verbose_name_plural': 'Episodes',
                'ordering': ['title'],
                'unique_together': {('title', 'url_video')},
            },
        ),
    ]
