# Generated by Django 5.1.4 on 2025-04-08 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0002_alter_episode_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='last_part',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WeekAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=100)),
                ('stable', models.BooleanField(default=True)),
                ('time', models.TimeField(help_text='Masalan: 15:30 ko‘rinishida vaqt kiriting')),
                ('anime_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='anime_app.anime')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
