# Generated by Django 5.1.4 on 2025-04-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0003_anime_last_part_weekanime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekanime',
            options={'ordering': ['day', 'time'], 'verbose_name': 'week', 'verbose_name_plural': 'Weeks'},
        ),
        migrations.AlterField(
            model_name='weekanime',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='weekanime',
            unique_together={('anime_info', 'day')},
        ),
    ]
