# Generated by Django 5.1.4 on 2025-04-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0004_alter_weekanime_options_alter_weekanime_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='english_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
